### ISSUE TITLE
Wallet Generation & Encryption

### ISSUE THREAD

**Issue by apbendi** [ScopeLift/kaspa-wallet#11]
* When a user w/o an existing wallet navigates to the homepage, they should be presented with a screen to enter a password and create a wallet

<img width="351" alt="Screen Shot 2020-06-30 at 2 52 51 PM" src="https://user-images.githubusercontent.com/1479802/86167330-56375c80-bae4-11ea-8653-f49454209eb3.png">

* After the user enters a password and hits create wallet, it should generate the secure randomness as the base for their HD wallet
* The randomness, in whatever form is most appropriate, should be encrypted using pbkdf2 and stored in local storage (perhaps using this module? https://www.npmjs.com/package/browser-passworder)
* The user should be taken to a base wallet page showing, for now, their first receive address derived
* When a user who has already created a wallet navigates to the homepage, they should be presented with a dialog to unlock their wallet with the password
 
<img width="342" alt="Screen Shot 2020-06-30 at 3 14 54 PM" src="https://user-images.githubusercontent.com/1479802/86167456-8a128200-bae4-11ea-99b7-e2d9575aa87a.png">

* Entering the correct password should decrypt the file and return them to the homepage

**Comment by wildmolasses** [comment]
types for browser-passworder: https://github.com/machinomy/types-browser-passworder/blob/master/index.d.ts
possible alternative library: https://github.com/ricmoo/scrypt-js
