### ISSUE TITLE
wallet should store utxo reference set

### ISSUE THREAD

**Issue by wildmolasses** [ScopeLift/kaspa-wallet#9]
c.f. [the bitcoin book](https://github.com/bitcoinbook/bitcoinbook/blob/develop/ch06.asciidoc#transaction-outputs-and-inputs):

> When we say that a user’s wallet has "received" bitcoin, what we mean is that the wallet has detected an UTXO that can be spent with one of the keys controlled by that wallet. Thus, a user’s bitcoin "balance" is the sum of all UTXO that user’s wallet can spend and which may be scattered among hundreds of transactions and hundreds of blocks. The concept of a balance is created by the wallet application. The wallet calculates the user’s balance by scanning the blockchain and aggregating the value of any UTXO the wallet can spend with the keys it controls. Most wallets maintain a database or use a database service to store a quick reference set of all the UTXO they can spend with the keys they control.

**Comment by Noah-svg** [comment]
现在交易所一般都不自己单独开发一套钱包系统了，通常API一键接入优盾钱包了吧，还可以余额一键归集，挺好用的
